# flake8: noqa

"""
    IoTVAS API

    IOTVAS API enables you to discover IoT/Connected devices in the network and provides      detailed real-time risk analysis, including firmware vulnerability analysis without requiring the user to upload the firmware file.     Please visit the [signup page](https://iotvas-api.firmalyzer.com/portal/signup) to create an API key.     IoTVAS API can be easily integrated with vulnerability scanning and network port scanner tools. For example,     we have also released the [IOTVAS NSE script](https://github.com/firmalyzer/iotvas-nmap) that turns the nmap port scanner      to a IoT/connected device discovery and real-time risk assessment tool. For more infromation on IoTVAS and other      solutions please visit [Firmalyzer web site](https://www.firmalyzer.com).  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


__version__ = "1"

# import ApiClient
from iotvas.api_client import ApiClient

# import Configuration
from iotvas.configuration import Configuration

# import exceptions
from iotvas.exceptions import OpenApiException
from iotvas.exceptions import ApiAttributeError
from iotvas.exceptions import ApiTypeError
from iotvas.exceptions import ApiValueError
from iotvas.exceptions import ApiKeyError
from iotvas.exceptions import ApiException
